on:
  push:
  pull_request:
  schedule:
    # Run every night to track nightly.
    - cron: '0 22 * * *'

name: CI

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      matrix:
        rust: [nightly]
        TARGET: [timer]

    steps:
      # Rust Setup
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rust-src
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # GCC Setup- Taken mostly from https://github.com/hathach/tinyusb/blob/master/.github/workflows/build.yml
      - name: Set toolchain URL (for cache)
        run: echo >> $GITHUB_ENV TOOLCHAIN_URL=http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/9_2_0_0/export/msp430-gcc-9.2.0.50_linux64.tar.bz2
      - uses: actions/cache@v2
        id: cache-msp430
        with:
          path: ~/cache/
          key: ${{ runner.os }}-${{ env.TOOLCHAIN_URL }}
      - name: Download msp430-gcc toolchain
        if: steps.cache-msp430.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/cache/toolchain
          wget $TOOLCHAIN_URL -nv -O toolchain.tar.bz2
          tar -xjf toolchain.tar.bz2 -C ~/cache/toolchain
      - name: Set toolchain path
        run: echo >> $GITHUB_PATH `echo ~/cache/toolchain/*/bin`
      # Build
      - name: Do build
        run: just ${{ matrix.TARGET }}
